// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXMyUmdHt4twToUwjSixUWeWBYSQnUAUg',
    appId: '1:1084270967806:web:0849dd6e8f01bab69f9eaf',
    messagingSenderId: '1084270967806',
    projectId: 'week-69e98',
    authDomain: 'week-69e98.firebaseapp.com',
    storageBucket: 'week-69e98.firebasestorage.app',
    measurementId: 'G-GL7Y45ZC45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJRotW0xKRTSpuiD_p_iBJSviCetEtiak',
    appId: '1:1084270967806:android:41af232ce86b594b9f9eaf',
    messagingSenderId: '1084270967806',
    projectId: 'week-69e98',
    storageBucket: 'week-69e98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcblgpgKtOTfIYFJbRlZnOE_txNLYPcqs',
    appId: '1:1084270967806:ios:68942479c2560e7a9f9eaf',
    messagingSenderId: '1084270967806',
    projectId: 'week-69e98',
    storageBucket: 'week-69e98.firebasestorage.app',
    iosBundleId: 'com.example.week8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcblgpgKtOTfIYFJbRlZnOE_txNLYPcqs',
    appId: '1:1084270967806:ios:68942479c2560e7a9f9eaf',
    messagingSenderId: '1084270967806',
    projectId: 'week-69e98',
    storageBucket: 'week-69e98.firebasestorage.app',
    iosBundleId: 'com.example.week8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXMyUmdHt4twToUwjSixUWeWBYSQnUAUg',
    appId: '1:1084270967806:web:1926c9cfe1f8954e9f9eaf',
    messagingSenderId: '1084270967806',
    projectId: 'week-69e98',
    authDomain: 'week-69e98.firebaseapp.com',
    storageBucket: 'week-69e98.firebasestorage.app',
    measurementId: 'G-BRHCF9YM23',
  );
}
